// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/doomforge.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/models.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'services/net.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1276462047;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_doomforge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiDoomforgeAiAnalyzeLog({
    required String apiKey,
    required String model,
    required String log,
    required List<String> loadOrder,
  });

  Future<String> crateApiDoomforgeAiDescribeBuild({
    required String apiKey,
    required String model,
    required List<String> mods,
  });

  Future<LogAnalysis> crateApiDoomforgeAnalyzeLogFile({
    required String path,
    required Profile profile,
  });

  Future<LogAnalysis> crateApiDoomforgeAnalyzeLogText({
    required String text,
    required Profile profile,
  });

  Future<List<LoadEntry>> crateApiDoomforgeAutoOrder({
    required List<LoadEntry> entries,
  });

  Future<List<PackageEntry>> crateApiDoomforgeCatalog();

  Future<List<Iwad>> crateApiDoomforgeCheckIwads({required List<String> dirs});

  Future<ProfileDiff> crateApiDoomforgeCompareProfiles({
    required Profile a,
    required Profile b,
  });

  Future<SnapshotMeta> crateApiDoomforgeCreateSnapshot({
    required Profile profile,
    required String label,
  });

  Future<void> crateApiDoomforgeDeleteProfile({required String id});

  Future<void> crateApiDoomforgeDeleteSnapshot({
    required String profileId,
    required String snapshotId,
  });

  Future<List<ModFile>> crateApiDoomforgeDescribeFiles({
    required List<String> paths,
  });

  Future<List<Engine>> crateApiDoomforgeDetectEngines();

  Future<String> crateApiDoomforgeDryRunProfile({
    required String engine,
    required Profile profile,
  });

  Future<CompatReport> crateApiDoomforgeEvaluateCompat({
    required Profile profile,
  });

  Future<void> crateApiDoomforgeExportProfile({
    required String id,
    required String dest,
  });

  Future<List<DuplicateGroup>> crateApiDoomforgeFindDuplicates({
    required List<ModFile> files,
  });

  Future<Profile> crateApiDoomforgeForgeBuild({
    required List<ModFile> library_,
    String? iwad,
  });

  Future<String> crateApiDoomforgeGenerateReport({required Profile profile});

  Future<Stability> crateApiDoomforgeGetStability({required String profileId});

  Future<List<PackageEntry>> crateApiDoomforgeIdgamesSearch({
    required String query,
  });

  Future<String> crateApiDoomforgeImportByUrl({
    required String url,
    required String destDir,
  });

  Future<Profile> crateApiDoomforgeImportProfile({required String src});

  Future<void> crateApiInitApp();

  Future<Engine> crateApiDoomforgeInspectEngine({required String path});

  Future<String> crateApiDoomforgeInstallCatalog({
    required String url,
    required String modsDir,
  });

  Future<List<String>> crateApiDoomforgeInstallFreedoom({
    required String iwadDir,
  });

  Future<String> crateApiDoomforgeInstallGzdoom({required String destDir});

  Future<String> crateApiDoomforgeInstallPackage({
    required String source,
    required String id,
    required String modsDir,
  });

  Future<String> crateApiDoomforgeLaunchProfile({
    required String engine,
    required Profile profile,
    required bool safeMode,
  });

  Future<List<Profile>> crateApiDoomforgeListProfiles();

  Future<List<SnapshotMeta>> crateApiDoomforgeListSnapshots({
    required String profileId,
  });

  Future<ModGraph> crateApiDoomforgeModGraph({required Profile profile});

  Future<List<Recommendation>> crateApiDoomforgeRecommendMods({
    required List<ModFile> library_,
    required Profile profile,
    required int limit,
  });

  Future<Stability> crateApiDoomforgeRecordOutcome({
    required String profileId,
    required bool crashed,
  });

  Future<Profile> crateApiDoomforgeRestoreSnapshot({
    required String profileId,
    required String snapshotId,
  });

  Future<Profile> crateApiDoomforgeSaveProfile({required Profile profile});

  Future<void> crateApiDoomforgeSaveText({
    required String dest,
    required String contents,
  });

  Future<List<Engine>> crateApiDoomforgeScanEngines({required String dir});

  Future<List<ModFile>> crateApiDoomforgeScanMods({
    required String dir,
    required bool withHashes,
  });

  Future<List<String>> crateApiDoomforgeSearchModContents({
    required List<ModFile> files,
    required String query,
  });

  Future<List<PackageEntry>> crateApiDoomforgeSearchRegistry({
    required String source,
    required String query,
  });

  Future<void> crateApiDoomforgeSetDataDir({required String dataDir});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiDoomforgeAiAnalyzeLog({
    required String apiKey,
    required String model,
    required String log,
    required List<String> loadOrder,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(apiKey, serializer);
          sse_encode_String(model, serializer);
          sse_encode_String(log, serializer);
          sse_encode_list_String(loadOrder, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeAiAnalyzeLogConstMeta,
        argValues: [apiKey, model, log, loadOrder],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeAiAnalyzeLogConstMeta =>
      const TaskConstMeta(
        debugName: "ai_analyze_log",
        argNames: ["apiKey", "model", "log", "loadOrder"],
      );

  @override
  Future<String> crateApiDoomforgeAiDescribeBuild({
    required String apiKey,
    required String model,
    required List<String> mods,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(apiKey, serializer);
          sse_encode_String(model, serializer);
          sse_encode_list_String(mods, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeAiDescribeBuildConstMeta,
        argValues: [apiKey, model, mods],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeAiDescribeBuildConstMeta =>
      const TaskConstMeta(
        debugName: "ai_describe_build",
        argNames: ["apiKey", "model", "mods"],
      );

  @override
  Future<LogAnalysis> crateApiDoomforgeAnalyzeLogFile({
    required String path,
    required Profile profile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_log_analysis,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeAnalyzeLogFileConstMeta,
        argValues: [path, profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeAnalyzeLogFileConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_log_file",
        argNames: ["path", "profile"],
      );

  @override
  Future<LogAnalysis> crateApiDoomforgeAnalyzeLogText({
    required String text,
    required Profile profile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_box_autoadd_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_log_analysis,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeAnalyzeLogTextConstMeta,
        argValues: [text, profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeAnalyzeLogTextConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_log_text",
        argNames: ["text", "profile"],
      );

  @override
  Future<List<LoadEntry>> crateApiDoomforgeAutoOrder({
    required List<LoadEntry> entries,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_load_entry(entries, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_load_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeAutoOrderConstMeta,
        argValues: [entries],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeAutoOrderConstMeta =>
      const TaskConstMeta(debugName: "auto_order", argNames: ["entries"]);

  @override
  Future<List<PackageEntry>> crateApiDoomforgeCatalog() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_package_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeCatalogConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeCatalogConstMeta =>
      const TaskConstMeta(debugName: "catalog", argNames: []);

  @override
  Future<List<Iwad>> crateApiDoomforgeCheckIwads({required List<String> dirs}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(dirs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_iwad,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeCheckIwadsConstMeta,
        argValues: [dirs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeCheckIwadsConstMeta =>
      const TaskConstMeta(debugName: "check_iwads", argNames: ["dirs"]);

  @override
  Future<ProfileDiff> crateApiDoomforgeCompareProfiles({
    required Profile a,
    required Profile b,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_profile(a, serializer);
          sse_encode_box_autoadd_profile(b, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile_diff,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeCompareProfilesConstMeta,
        argValues: [a, b],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeCompareProfilesConstMeta =>
      const TaskConstMeta(debugName: "compare_profiles", argNames: ["a", "b"]);

  @override
  Future<SnapshotMeta> crateApiDoomforgeCreateSnapshot({
    required Profile profile,
    required String label,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_profile(profile, serializer);
          sse_encode_String(label, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_snapshot_meta,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeCreateSnapshotConstMeta,
        argValues: [profile, label],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeCreateSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "create_snapshot",
        argNames: ["profile", "label"],
      );

  @override
  Future<void> crateApiDoomforgeDeleteProfile({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeDeleteProfileConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeDeleteProfileConstMeta =>
      const TaskConstMeta(debugName: "delete_profile", argNames: ["id"]);

  @override
  Future<void> crateApiDoomforgeDeleteSnapshot({
    required String profileId,
    required String snapshotId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          sse_encode_String(snapshotId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeDeleteSnapshotConstMeta,
        argValues: [profileId, snapshotId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeDeleteSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "delete_snapshot",
        argNames: ["profileId", "snapshotId"],
      );

  @override
  Future<List<ModFile>> crateApiDoomforgeDescribeFiles({
    required List<String> paths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(paths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mod_file,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeDescribeFilesConstMeta,
        argValues: [paths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeDescribeFilesConstMeta =>
      const TaskConstMeta(debugName: "describe_files", argNames: ["paths"]);

  @override
  Future<List<Engine>> crateApiDoomforgeDetectEngines() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_engine,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeDetectEnginesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeDetectEnginesConstMeta =>
      const TaskConstMeta(debugName: "detect_engines", argNames: []);

  @override
  Future<String> crateApiDoomforgeDryRunProfile({
    required String engine,
    required Profile profile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(engine, serializer);
          sse_encode_box_autoadd_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeDryRunProfileConstMeta,
        argValues: [engine, profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeDryRunProfileConstMeta =>
      const TaskConstMeta(
        debugName: "dry_run_profile",
        argNames: ["engine", "profile"],
      );

  @override
  Future<CompatReport> crateApiDoomforgeEvaluateCompat({
    required Profile profile,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_compat_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeEvaluateCompatConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeEvaluateCompatConstMeta =>
      const TaskConstMeta(debugName: "evaluate_compat", argNames: ["profile"]);

  @override
  Future<void> crateApiDoomforgeExportProfile({
    required String id,
    required String dest,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_String(dest, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeExportProfileConstMeta,
        argValues: [id, dest],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeExportProfileConstMeta =>
      const TaskConstMeta(
        debugName: "export_profile",
        argNames: ["id", "dest"],
      );

  @override
  Future<List<DuplicateGroup>> crateApiDoomforgeFindDuplicates({
    required List<ModFile> files,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_mod_file(files, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_duplicate_group,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeFindDuplicatesConstMeta,
        argValues: [files],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeFindDuplicatesConstMeta =>
      const TaskConstMeta(debugName: "find_duplicates", argNames: ["files"]);

  @override
  Future<Profile> crateApiDoomforgeForgeBuild({
    required List<ModFile> library_,
    String? iwad,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_mod_file(library_, serializer);
          sse_encode_opt_String(iwad, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeForgeBuildConstMeta,
        argValues: [library_, iwad],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeForgeBuildConstMeta =>
      const TaskConstMeta(
        debugName: "forge_build",
        argNames: ["library_", "iwad"],
      );

  @override
  Future<String> crateApiDoomforgeGenerateReport({required Profile profile}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeGenerateReportConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeGenerateReportConstMeta =>
      const TaskConstMeta(debugName: "generate_report", argNames: ["profile"]);

  @override
  Future<Stability> crateApiDoomforgeGetStability({required String profileId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stability,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeGetStabilityConstMeta,
        argValues: [profileId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeGetStabilityConstMeta =>
      const TaskConstMeta(debugName: "get_stability", argNames: ["profileId"]);

  @override
  Future<List<PackageEntry>> crateApiDoomforgeIdgamesSearch({
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_package_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeIdgamesSearchConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeIdgamesSearchConstMeta =>
      const TaskConstMeta(debugName: "idgames_search", argNames: ["query"]);

  @override
  Future<String> crateApiDoomforgeImportByUrl({
    required String url,
    required String destDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(destDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeImportByUrlConstMeta,
        argValues: [url, destDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeImportByUrlConstMeta =>
      const TaskConstMeta(
        debugName: "import_by_url",
        argNames: ["url", "destDir"],
      );

  @override
  Future<Profile> crateApiDoomforgeImportProfile({required String src}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(src, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeImportProfileConstMeta,
        argValues: [src],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeImportProfileConstMeta =>
      const TaskConstMeta(debugName: "import_profile", argNames: ["src"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<Engine> crateApiDoomforgeInspectEngine({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_engine,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeInspectEngineConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeInspectEngineConstMeta =>
      const TaskConstMeta(debugName: "inspect_engine", argNames: ["path"]);

  @override
  Future<String> crateApiDoomforgeInstallCatalog({
    required String url,
    required String modsDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(url, serializer);
          sse_encode_String(modsDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeInstallCatalogConstMeta,
        argValues: [url, modsDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeInstallCatalogConstMeta =>
      const TaskConstMeta(
        debugName: "install_catalog",
        argNames: ["url", "modsDir"],
      );

  @override
  Future<List<String>> crateApiDoomforgeInstallFreedoom({
    required String iwadDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(iwadDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeInstallFreedoomConstMeta,
        argValues: [iwadDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeInstallFreedoomConstMeta =>
      const TaskConstMeta(debugName: "install_freedoom", argNames: ["iwadDir"]);

  @override
  Future<String> crateApiDoomforgeInstallGzdoom({required String destDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(destDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeInstallGzdoomConstMeta,
        argValues: [destDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeInstallGzdoomConstMeta =>
      const TaskConstMeta(debugName: "install_gzdoom", argNames: ["destDir"]);

  @override
  Future<String> crateApiDoomforgeInstallPackage({
    required String source,
    required String id,
    required String modsDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_String(id, serializer);
          sse_encode_String(modsDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeInstallPackageConstMeta,
        argValues: [source, id, modsDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeInstallPackageConstMeta =>
      const TaskConstMeta(
        debugName: "install_package",
        argNames: ["source", "id", "modsDir"],
      );

  @override
  Future<String> crateApiDoomforgeLaunchProfile({
    required String engine,
    required Profile profile,
    required bool safeMode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(engine, serializer);
          sse_encode_box_autoadd_profile(profile, serializer);
          sse_encode_bool(safeMode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeLaunchProfileConstMeta,
        argValues: [engine, profile, safeMode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeLaunchProfileConstMeta =>
      const TaskConstMeta(
        debugName: "launch_profile",
        argNames: ["engine", "profile", "safeMode"],
      );

  @override
  Future<List<Profile>> crateApiDoomforgeListProfiles() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_profile,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeListProfilesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeListProfilesConstMeta =>
      const TaskConstMeta(debugName: "list_profiles", argNames: []);

  @override
  Future<List<SnapshotMeta>> crateApiDoomforgeListSnapshots({
    required String profileId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_snapshot_meta,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeListSnapshotsConstMeta,
        argValues: [profileId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeListSnapshotsConstMeta =>
      const TaskConstMeta(debugName: "list_snapshots", argNames: ["profileId"]);

  @override
  Future<ModGraph> crateApiDoomforgeModGraph({required Profile profile}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mod_graph,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeModGraphConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeModGraphConstMeta =>
      const TaskConstMeta(debugName: "mod_graph", argNames: ["profile"]);

  @override
  Future<List<Recommendation>> crateApiDoomforgeRecommendMods({
    required List<ModFile> library_,
    required Profile profile,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_mod_file(library_, serializer);
          sse_encode_box_autoadd_profile(profile, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_recommendation,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeRecommendModsConstMeta,
        argValues: [library_, profile, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeRecommendModsConstMeta =>
      const TaskConstMeta(
        debugName: "recommend_mods",
        argNames: ["library_", "profile", "limit"],
      );

  @override
  Future<Stability> crateApiDoomforgeRecordOutcome({
    required String profileId,
    required bool crashed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          sse_encode_bool(crashed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stability,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeRecordOutcomeConstMeta,
        argValues: [profileId, crashed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeRecordOutcomeConstMeta =>
      const TaskConstMeta(
        debugName: "record_outcome",
        argNames: ["profileId", "crashed"],
      );

  @override
  Future<Profile> crateApiDoomforgeRestoreSnapshot({
    required String profileId,
    required String snapshotId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(profileId, serializer);
          sse_encode_String(snapshotId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeRestoreSnapshotConstMeta,
        argValues: [profileId, snapshotId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeRestoreSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "restore_snapshot",
        argNames: ["profileId", "snapshotId"],
      );

  @override
  Future<Profile> crateApiDoomforgeSaveProfile({required Profile profile}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_profile(profile, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_profile,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeSaveProfileConstMeta,
        argValues: [profile],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeSaveProfileConstMeta =>
      const TaskConstMeta(debugName: "save_profile", argNames: ["profile"]);

  @override
  Future<void> crateApiDoomforgeSaveText({
    required String dest,
    required String contents,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dest, serializer);
          sse_encode_String(contents, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeSaveTextConstMeta,
        argValues: [dest, contents],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeSaveTextConstMeta => const TaskConstMeta(
    debugName: "save_text",
    argNames: ["dest", "contents"],
  );

  @override
  Future<List<Engine>> crateApiDoomforgeScanEngines({required String dir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_engine,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeScanEnginesConstMeta,
        argValues: [dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeScanEnginesConstMeta =>
      const TaskConstMeta(debugName: "scan_engines", argNames: ["dir"]);

  @override
  Future<List<ModFile>> crateApiDoomforgeScanMods({
    required String dir,
    required bool withHashes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          sse_encode_bool(withHashes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mod_file,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeScanModsConstMeta,
        argValues: [dir, withHashes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeScanModsConstMeta => const TaskConstMeta(
    debugName: "scan_mods",
    argNames: ["dir", "withHashes"],
  );

  @override
  Future<List<String>> crateApiDoomforgeSearchModContents({
    required List<ModFile> files,
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_mod_file(files, serializer);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeSearchModContentsConstMeta,
        argValues: [files, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeSearchModContentsConstMeta =>
      const TaskConstMeta(
        debugName: "search_mod_contents",
        argNames: ["files", "query"],
      );

  @override
  Future<List<PackageEntry>> crateApiDoomforgeSearchRegistry({
    required String source,
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_package_entry,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDoomforgeSearchRegistryConstMeta,
        argValues: [source, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeSearchRegistryConstMeta =>
      const TaskConstMeta(
        debugName: "search_registry",
        argNames: ["source", "query"],
      );

  @override
  Future<void> crateApiDoomforgeSetDataDir({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDoomforgeSetDataDirConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDoomforgeSetDataDirConstMeta =>
      const TaskConstMeta(debugName: "set_data_dir", argNames: ["dataDir"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Profile dco_decode_box_autoadd_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_profile(raw);
  }

  @protected
  CompatReport dco_decode_compat_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CompatReport(
      score: dco_decode_u_8(arr[0]),
      hits: dco_decode_list_conflict_hit(arr[1]),
      warnings: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  ConflictHit dco_decode_conflict_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ConflictHit(
      a: dco_decode_String(arr[0]),
      b: dco_decode_String(arr[1]),
      severity: dco_decode_String(arr[2]),
      note: dco_decode_String(arr[3]),
      patch: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  DuplicateGroup dco_decode_duplicate_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DuplicateGroup(
      reason: dco_decode_String(arr[0]),
      files: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  Engine dco_decode_engine(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Engine(
      path: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      version: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GraphEdge dco_decode_graph_edge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GraphEdge(
      from: dco_decode_String(arr[0]),
      to: dco_decode_String(arr[1]),
      kind: dco_decode_String(arr[2]),
    );
  }

  @protected
  GraphNode dco_decode_graph_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return GraphNode(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      group: dco_decode_mod_group(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Iwad dco_decode_iwad(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Iwad(
      fileName: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      path: dco_decode_opt_String(arr[2]),
      present: dco_decode_bool(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConflictHit> dco_decode_list_conflict_hit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_conflict_hit).toList();
  }

  @protected
  List<DuplicateGroup> dco_decode_list_duplicate_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_duplicate_group).toList();
  }

  @protected
  List<Engine> dco_decode_list_engine(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_engine).toList();
  }

  @protected
  List<GraphEdge> dco_decode_list_graph_edge(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_graph_edge).toList();
  }

  @protected
  List<GraphNode> dco_decode_list_graph_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_graph_node).toList();
  }

  @protected
  List<Iwad> dco_decode_list_iwad(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_iwad).toList();
  }

  @protected
  List<LoadEntry> dco_decode_list_load_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_load_entry).toList();
  }

  @protected
  List<ModFile> dco_decode_list_mod_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mod_file).toList();
  }

  @protected
  List<PackageEntry> dco_decode_list_package_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_package_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Profile> dco_decode_list_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_profile).toList();
  }

  @protected
  List<Recommendation> dco_decode_list_recommendation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_recommendation).toList();
  }

  @protected
  List<SnapshotMeta> dco_decode_list_snapshot_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_snapshot_meta).toList();
  }

  @protected
  LoadEntry dco_decode_load_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LoadEntry(
      path: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      group: dco_decode_mod_group(arr[2]),
      enabled: dco_decode_bool(arr[3]),
    );
  }

  @protected
  LogAnalysis dco_decode_log_analysis(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LogAnalysis(
      summary: dco_decode_String(arr[0]),
      suspectMods: dco_decode_list_String(arr[1]),
      signals: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  ModFile dco_decode_mod_file(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ModFile(
      path: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      extension_: dco_decode_String(arr[2]),
      size: dco_decode_u_64(arr[3]),
      sha256: dco_decode_opt_String(arr[4]),
      group: dco_decode_mod_group(arr[5]),
      tags: dco_decode_list_String(arr[6]),
    );
  }

  @protected
  ModGraph dco_decode_mod_graph(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ModGraph(
      nodes: dco_decode_list_graph_node(arr[0]),
      edges: dco_decode_list_graph_edge(arr[1]),
    );
  }

  @protected
  ModGroup dco_decode_mod_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ModGroup.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PackageEntry dco_decode_package_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PackageEntry(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
      version: dco_decode_String(arr[3]),
      url: dco_decode_String(arr[4]),
      tags: dco_decode_list_String(arr[5]),
      homepage: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  Profile dco_decode_profile(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return Profile(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      description: dco_decode_String(arr[2]),
      enginePath: dco_decode_opt_String(arr[3]),
      iwad: dco_decode_opt_String(arr[4]),
      loadOrder: dco_decode_list_load_entry(arr[5]),
      extraArgs: dco_decode_list_String(arr[6]),
      createdAt: dco_decode_String(arr[7]),
      updatedAt: dco_decode_String(arr[8]),
      lastPlayedAt: dco_decode_opt_String(arr[9]),
    );
  }

  @protected
  ProfileDiff dco_decode_profile_diff(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProfileDiff(
      onlyInA: dco_decode_list_String(arr[0]),
      onlyInB: dco_decode_list_String(arr[1]),
      common: dco_decode_list_String(arr[2]),
      reordered: dco_decode_bool(arr[3]),
    );
  }

  @protected
  Recommendation dco_decode_recommendation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Recommendation(
      path: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      group: dco_decode_mod_group(arr[2]),
      reason: dco_decode_String(arr[3]),
      score: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  SnapshotMeta dco_decode_snapshot_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SnapshotMeta(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      createdAt: dco_decode_String(arr[2]),
      entryCount: dco_decode_usize(arr[3]),
    );
  }

  @protected
  Stability dco_decode_stability(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Stability(
      launches: dco_decode_u_32(arr[0]),
      crashes: dco_decode_u_32(arr[1]),
      rating: dco_decode_u_8(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Profile sse_decode_box_autoadd_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_profile(deserializer));
  }

  @protected
  CompatReport sse_decode_compat_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_score = sse_decode_u_8(deserializer);
    var var_hits = sse_decode_list_conflict_hit(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    return CompatReport(
      score: var_score,
      hits: var_hits,
      warnings: var_warnings,
    );
  }

  @protected
  ConflictHit sse_decode_conflict_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_a = sse_decode_String(deserializer);
    var var_b = sse_decode_String(deserializer);
    var var_severity = sse_decode_String(deserializer);
    var var_note = sse_decode_String(deserializer);
    var var_patch = sse_decode_opt_String(deserializer);
    return ConflictHit(
      a: var_a,
      b: var_b,
      severity: var_severity,
      note: var_note,
      patch: var_patch,
    );
  }

  @protected
  DuplicateGroup sse_decode_duplicate_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_reason = sse_decode_String(deserializer);
    var var_files = sse_decode_list_String(deserializer);
    return DuplicateGroup(reason: var_reason, files: var_files);
  }

  @protected
  Engine sse_decode_engine(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_version = sse_decode_opt_String(deserializer);
    return Engine(path: var_path, name: var_name, version: var_version);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  GraphEdge sse_decode_graph_edge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_from = sse_decode_String(deserializer);
    var var_to = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    return GraphEdge(from: var_from, to: var_to, kind: var_kind);
  }

  @protected
  GraphNode sse_decode_graph_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_group = sse_decode_mod_group(deserializer);
    return GraphNode(id: var_id, name: var_name, group: var_group);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Iwad sse_decode_iwad(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fileName = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_path = sse_decode_opt_String(deserializer);
    var var_present = sse_decode_bool(deserializer);
    return Iwad(
      fileName: var_fileName,
      title: var_title,
      path: var_path,
      present: var_present,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConflictHit> sse_decode_list_conflict_hit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConflictHit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_conflict_hit(deserializer));
    }
    return ans_;
  }

  @protected
  List<DuplicateGroup> sse_decode_list_duplicate_group(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DuplicateGroup>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_duplicate_group(deserializer));
    }
    return ans_;
  }

  @protected
  List<Engine> sse_decode_list_engine(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Engine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_engine(deserializer));
    }
    return ans_;
  }

  @protected
  List<GraphEdge> sse_decode_list_graph_edge(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GraphEdge>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_graph_edge(deserializer));
    }
    return ans_;
  }

  @protected
  List<GraphNode> sse_decode_list_graph_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GraphNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_graph_node(deserializer));
    }
    return ans_;
  }

  @protected
  List<Iwad> sse_decode_list_iwad(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Iwad>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_iwad(deserializer));
    }
    return ans_;
  }

  @protected
  List<LoadEntry> sse_decode_list_load_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LoadEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_load_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModFile> sse_decode_list_mod_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModFile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mod_file(deserializer));
    }
    return ans_;
  }

  @protected
  List<PackageEntry> sse_decode_list_package_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PackageEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_package_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Profile> sse_decode_list_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Profile>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_profile(deserializer));
    }
    return ans_;
  }

  @protected
  List<Recommendation> sse_decode_list_recommendation(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Recommendation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_recommendation(deserializer));
    }
    return ans_;
  }

  @protected
  List<SnapshotMeta> sse_decode_list_snapshot_meta(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SnapshotMeta>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_snapshot_meta(deserializer));
    }
    return ans_;
  }

  @protected
  LoadEntry sse_decode_load_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_group = sse_decode_mod_group(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    return LoadEntry(
      path: var_path,
      name: var_name,
      group: var_group,
      enabled: var_enabled,
    );
  }

  @protected
  LogAnalysis sse_decode_log_analysis(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_summary = sse_decode_String(deserializer);
    var var_suspectMods = sse_decode_list_String(deserializer);
    var var_signals = sse_decode_list_String(deserializer);
    return LogAnalysis(
      summary: var_summary,
      suspectMods: var_suspectMods,
      signals: var_signals,
    );
  }

  @protected
  ModFile sse_decode_mod_file(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_extension_ = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_sha256 = sse_decode_opt_String(deserializer);
    var var_group = sse_decode_mod_group(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return ModFile(
      path: var_path,
      name: var_name,
      extension_: var_extension_,
      size: var_size,
      sha256: var_sha256,
      group: var_group,
      tags: var_tags,
    );
  }

  @protected
  ModGraph sse_decode_mod_graph(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodes = sse_decode_list_graph_node(deserializer);
    var var_edges = sse_decode_list_graph_edge(deserializer);
    return ModGraph(nodes: var_nodes, edges: var_edges);
  }

  @protected
  ModGroup sse_decode_mod_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ModGroup.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PackageEntry sse_decode_package_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_homepage = sse_decode_opt_String(deserializer);
    return PackageEntry(
      id: var_id,
      name: var_name,
      description: var_description,
      version: var_version,
      url: var_url,
      tags: var_tags,
      homepage: var_homepage,
    );
  }

  @protected
  Profile sse_decode_profile(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_enginePath = sse_decode_opt_String(deserializer);
    var var_iwad = sse_decode_opt_String(deserializer);
    var var_loadOrder = sse_decode_list_load_entry(deserializer);
    var var_extraArgs = sse_decode_list_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    var var_lastPlayedAt = sse_decode_opt_String(deserializer);
    return Profile(
      id: var_id,
      name: var_name,
      description: var_description,
      enginePath: var_enginePath,
      iwad: var_iwad,
      loadOrder: var_loadOrder,
      extraArgs: var_extraArgs,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
      lastPlayedAt: var_lastPlayedAt,
    );
  }

  @protected
  ProfileDiff sse_decode_profile_diff(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_onlyInA = sse_decode_list_String(deserializer);
    var var_onlyInB = sse_decode_list_String(deserializer);
    var var_common = sse_decode_list_String(deserializer);
    var var_reordered = sse_decode_bool(deserializer);
    return ProfileDiff(
      onlyInA: var_onlyInA,
      onlyInB: var_onlyInB,
      common: var_common,
      reordered: var_reordered,
    );
  }

  @protected
  Recommendation sse_decode_recommendation(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_group = sse_decode_mod_group(deserializer);
    var var_reason = sse_decode_String(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    return Recommendation(
      path: var_path,
      name: var_name,
      group: var_group,
      reason: var_reason,
      score: var_score,
    );
  }

  @protected
  SnapshotMeta sse_decode_snapshot_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_entryCount = sse_decode_usize(deserializer);
    return SnapshotMeta(
      id: var_id,
      label: var_label,
      createdAt: var_createdAt,
      entryCount: var_entryCount,
    );
  }

  @protected
  Stability sse_decode_stability(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_launches = sse_decode_u_32(deserializer);
    var var_crashes = sse_decode_u_32(deserializer);
    var var_rating = sse_decode_u_8(deserializer);
    return Stability(
      launches: var_launches,
      crashes: var_crashes,
      rating: var_rating,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_profile(Profile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_profile(self, serializer);
  }

  @protected
  void sse_encode_compat_report(CompatReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.score, serializer);
    sse_encode_list_conflict_hit(self.hits, serializer);
    sse_encode_list_String(self.warnings, serializer);
  }

  @protected
  void sse_encode_conflict_hit(ConflictHit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.a, serializer);
    sse_encode_String(self.b, serializer);
    sse_encode_String(self.severity, serializer);
    sse_encode_String(self.note, serializer);
    sse_encode_opt_String(self.patch, serializer);
  }

  @protected
  void sse_encode_duplicate_group(
    DuplicateGroup self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.reason, serializer);
    sse_encode_list_String(self.files, serializer);
  }

  @protected
  void sse_encode_engine(Engine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.version, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_graph_edge(GraphEdge self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.from, serializer);
    sse_encode_String(self.to, serializer);
    sse_encode_String(self.kind, serializer);
  }

  @protected
  void sse_encode_graph_node(GraphNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_mod_group(self.group, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_iwad(Iwad self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_String(self.path, serializer);
    sse_encode_bool(self.present, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_conflict_hit(
    List<ConflictHit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_conflict_hit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_duplicate_group(
    List<DuplicateGroup> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_duplicate_group(item, serializer);
    }
  }

  @protected
  void sse_encode_list_engine(List<Engine> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_engine(item, serializer);
    }
  }

  @protected
  void sse_encode_list_graph_edge(
    List<GraphEdge> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_graph_edge(item, serializer);
    }
  }

  @protected
  void sse_encode_list_graph_node(
    List<GraphNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_graph_node(item, serializer);
    }
  }

  @protected
  void sse_encode_list_iwad(List<Iwad> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_iwad(item, serializer);
    }
  }

  @protected
  void sse_encode_list_load_entry(
    List<LoadEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_load_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mod_file(List<ModFile> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mod_file(item, serializer);
    }
  }

  @protected
  void sse_encode_list_package_entry(
    List<PackageEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_package_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_profile(List<Profile> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_profile(item, serializer);
    }
  }

  @protected
  void sse_encode_list_recommendation(
    List<Recommendation> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_recommendation(item, serializer);
    }
  }

  @protected
  void sse_encode_list_snapshot_meta(
    List<SnapshotMeta> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_snapshot_meta(item, serializer);
    }
  }

  @protected
  void sse_encode_load_entry(LoadEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_mod_group(self.group, serializer);
    sse_encode_bool(self.enabled, serializer);
  }

  @protected
  void sse_encode_log_analysis(LogAnalysis self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.summary, serializer);
    sse_encode_list_String(self.suspectMods, serializer);
    sse_encode_list_String(self.signals, serializer);
  }

  @protected
  void sse_encode_mod_file(ModFile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.extension_, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_opt_String(self.sha256, serializer);
    sse_encode_mod_group(self.group, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_mod_graph(ModGraph self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_graph_node(self.nodes, serializer);
    sse_encode_list_graph_edge(self.edges, serializer);
  }

  @protected
  void sse_encode_mod_group(ModGroup self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_package_entry(PackageEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_String(self.homepage, serializer);
  }

  @protected
  void sse_encode_profile(Profile self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_opt_String(self.enginePath, serializer);
    sse_encode_opt_String(self.iwad, serializer);
    sse_encode_list_load_entry(self.loadOrder, serializer);
    sse_encode_list_String(self.extraArgs, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
    sse_encode_opt_String(self.lastPlayedAt, serializer);
  }

  @protected
  void sse_encode_profile_diff(ProfileDiff self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.onlyInA, serializer);
    sse_encode_list_String(self.onlyInB, serializer);
    sse_encode_list_String(self.common, serializer);
    sse_encode_bool(self.reordered, serializer);
  }

  @protected
  void sse_encode_recommendation(
    Recommendation self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_mod_group(self.group, serializer);
    sse_encode_String(self.reason, serializer);
    sse_encode_f_32(self.score, serializer);
  }

  @protected
  void sse_encode_snapshot_meta(SnapshotMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_usize(self.entryCount, serializer);
  }

  @protected
  void sse_encode_stability(Stability self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.launches, serializer);
    sse_encode_u_32(self.crashes, serializer);
    sse_encode_u_8(self.rating, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
