// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/doomforge.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/models.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'services/net.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Profile dco_decode_box_autoadd_profile(dynamic raw);

  @protected
  CompatReport dco_decode_compat_report(dynamic raw);

  @protected
  ConflictHit dco_decode_conflict_hit(dynamic raw);

  @protected
  DuplicateGroup dco_decode_duplicate_group(dynamic raw);

  @protected
  Engine dco_decode_engine(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  GraphEdge dco_decode_graph_edge(dynamic raw);

  @protected
  GraphNode dco_decode_graph_node(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  Iwad dco_decode_iwad(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ConflictHit> dco_decode_list_conflict_hit(dynamic raw);

  @protected
  List<DuplicateGroup> dco_decode_list_duplicate_group(dynamic raw);

  @protected
  List<Engine> dco_decode_list_engine(dynamic raw);

  @protected
  List<GraphEdge> dco_decode_list_graph_edge(dynamic raw);

  @protected
  List<GraphNode> dco_decode_list_graph_node(dynamic raw);

  @protected
  List<Iwad> dco_decode_list_iwad(dynamic raw);

  @protected
  List<LoadEntry> dco_decode_list_load_entry(dynamic raw);

  @protected
  List<ModFile> dco_decode_list_mod_file(dynamic raw);

  @protected
  List<PackageEntry> dco_decode_list_package_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Profile> dco_decode_list_profile(dynamic raw);

  @protected
  List<Recommendation> dco_decode_list_recommendation(dynamic raw);

  @protected
  List<SnapshotMeta> dco_decode_list_snapshot_meta(dynamic raw);

  @protected
  LoadEntry dco_decode_load_entry(dynamic raw);

  @protected
  LogAnalysis dco_decode_log_analysis(dynamic raw);

  @protected
  ModFile dco_decode_mod_file(dynamic raw);

  @protected
  ModGraph dco_decode_mod_graph(dynamic raw);

  @protected
  ModGroup dco_decode_mod_group(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PackageEntry dco_decode_package_entry(dynamic raw);

  @protected
  Profile dco_decode_profile(dynamic raw);

  @protected
  ProfileDiff dco_decode_profile_diff(dynamic raw);

  @protected
  Recommendation dco_decode_recommendation(dynamic raw);

  @protected
  SnapshotMeta dco_decode_snapshot_meta(dynamic raw);

  @protected
  Stability dco_decode_stability(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Profile sse_decode_box_autoadd_profile(SseDeserializer deserializer);

  @protected
  CompatReport sse_decode_compat_report(SseDeserializer deserializer);

  @protected
  ConflictHit sse_decode_conflict_hit(SseDeserializer deserializer);

  @protected
  DuplicateGroup sse_decode_duplicate_group(SseDeserializer deserializer);

  @protected
  Engine sse_decode_engine(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  GraphEdge sse_decode_graph_edge(SseDeserializer deserializer);

  @protected
  GraphNode sse_decode_graph_node(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  Iwad sse_decode_iwad(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ConflictHit> sse_decode_list_conflict_hit(SseDeserializer deserializer);

  @protected
  List<DuplicateGroup> sse_decode_list_duplicate_group(
    SseDeserializer deserializer,
  );

  @protected
  List<Engine> sse_decode_list_engine(SseDeserializer deserializer);

  @protected
  List<GraphEdge> sse_decode_list_graph_edge(SseDeserializer deserializer);

  @protected
  List<GraphNode> sse_decode_list_graph_node(SseDeserializer deserializer);

  @protected
  List<Iwad> sse_decode_list_iwad(SseDeserializer deserializer);

  @protected
  List<LoadEntry> sse_decode_list_load_entry(SseDeserializer deserializer);

  @protected
  List<ModFile> sse_decode_list_mod_file(SseDeserializer deserializer);

  @protected
  List<PackageEntry> sse_decode_list_package_entry(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Profile> sse_decode_list_profile(SseDeserializer deserializer);

  @protected
  List<Recommendation> sse_decode_list_recommendation(
    SseDeserializer deserializer,
  );

  @protected
  List<SnapshotMeta> sse_decode_list_snapshot_meta(
    SseDeserializer deserializer,
  );

  @protected
  LoadEntry sse_decode_load_entry(SseDeserializer deserializer);

  @protected
  LogAnalysis sse_decode_log_analysis(SseDeserializer deserializer);

  @protected
  ModFile sse_decode_mod_file(SseDeserializer deserializer);

  @protected
  ModGraph sse_decode_mod_graph(SseDeserializer deserializer);

  @protected
  ModGroup sse_decode_mod_group(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PackageEntry sse_decode_package_entry(SseDeserializer deserializer);

  @protected
  Profile sse_decode_profile(SseDeserializer deserializer);

  @protected
  ProfileDiff sse_decode_profile_diff(SseDeserializer deserializer);

  @protected
  Recommendation sse_decode_recommendation(SseDeserializer deserializer);

  @protected
  SnapshotMeta sse_decode_snapshot_meta(SseDeserializer deserializer);

  @protected
  Stability sse_decode_stability(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_profile(Profile self, SseSerializer serializer);

  @protected
  void sse_encode_compat_report(CompatReport self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_hit(ConflictHit self, SseSerializer serializer);

  @protected
  void sse_encode_duplicate_group(
    DuplicateGroup self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_engine(Engine self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_graph_edge(GraphEdge self, SseSerializer serializer);

  @protected
  void sse_encode_graph_node(GraphNode self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_iwad(Iwad self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conflict_hit(
    List<ConflictHit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_duplicate_group(
    List<DuplicateGroup> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_engine(List<Engine> self, SseSerializer serializer);

  @protected
  void sse_encode_list_graph_edge(
    List<GraphEdge> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_graph_node(
    List<GraphNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_iwad(List<Iwad> self, SseSerializer serializer);

  @protected
  void sse_encode_list_load_entry(
    List<LoadEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mod_file(List<ModFile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_package_entry(
    List<PackageEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_profile(List<Profile> self, SseSerializer serializer);

  @protected
  void sse_encode_list_recommendation(
    List<Recommendation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_snapshot_meta(
    List<SnapshotMeta> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_load_entry(LoadEntry self, SseSerializer serializer);

  @protected
  void sse_encode_log_analysis(LogAnalysis self, SseSerializer serializer);

  @protected
  void sse_encode_mod_file(ModFile self, SseSerializer serializer);

  @protected
  void sse_encode_mod_graph(ModGraph self, SseSerializer serializer);

  @protected
  void sse_encode_mod_group(ModGroup self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_package_entry(PackageEntry self, SseSerializer serializer);

  @protected
  void sse_encode_profile(Profile self, SseSerializer serializer);

  @protected
  void sse_encode_profile_diff(ProfileDiff self, SseSerializer serializer);

  @protected
  void sse_encode_recommendation(Recommendation self, SseSerializer serializer);

  @protected
  void sse_encode_snapshot_meta(SnapshotMeta self, SseSerializer serializer);

  @protected
  void sse_encode_stability(Stability self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
