// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Result of evaluating a profile's compatibility.
class CompatReport {
  /// 0..=100. 100 == no detected problems.
  final int score;
  final List<ConflictHit> hits;
  final List<String> warnings;

  const CompatReport({
    required this.score,
    required this.hits,
    required this.warnings,
  });

  @override
  int get hashCode => score.hashCode ^ hits.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompatReport &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          hits == other.hits &&
          warnings == other.warnings;
}

/// A conflict detected within a concrete load order.
class ConflictHit {
  final String a;
  final String b;
  final String severity;
  final String note;
  final String? patch;

  const ConflictHit({
    required this.a,
    required this.b,
    required this.severity,
    required this.note,
    this.patch,
  });

  @override
  int get hashCode =>
      a.hashCode ^
      b.hashCode ^
      severity.hashCode ^
      note.hashCode ^
      patch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConflictHit &&
          runtimeType == other.runtimeType &&
          a == other.a &&
          b == other.b &&
          severity == other.severity &&
          note == other.note &&
          patch == other.patch;
}

/// Two files that look like duplicates of each other.
class DuplicateGroup {
  final String reason;
  final List<String> files;

  const DuplicateGroup({required this.reason, required this.files});

  @override
  int get hashCode => reason.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DuplicateGroup &&
          runtimeType == other.runtimeType &&
          reason == other.reason &&
          files == other.files;
}

/// A detected source-port executable.
class Engine {
  final String path;
  final String name;

  /// Parsed version string, e.g. "4.12.2". None if it couldn't be read.
  final String? version;

  const Engine({required this.path, required this.name, this.version});

  @override
  int get hashCode => path.hashCode ^ name.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Engine &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          version == other.version;
}

/// A single edge in the mod dependency / relationship graph.
class GraphEdge {
  final String from;
  final String to;

  /// "order" | "conflict".
  final String kind;

  const GraphEdge({required this.from, required this.to, required this.kind});

  @override
  int get hashCode => from.hashCode ^ to.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphEdge &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to &&
          kind == other.kind;
}

class GraphNode {
  final String id;
  final String name;
  final ModGroup group;

  const GraphNode({required this.id, required this.name, required this.group});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ group.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          group == other.group;
}

/// An IWAD (commercial/freeware base game data) and whether it was found.
class Iwad {
  /// Canonical filename, e.g. "doom2.wad".
  final String fileName;

  /// Human label, e.g. "DOOM II: Hell on Earth".
  final String title;
  final String? path;
  final bool present;

  const Iwad({
    required this.fileName,
    required this.title,
    this.path,
    required this.present,
  });

  @override
  int get hashCode =>
      fileName.hashCode ^ title.hashCode ^ path.hashCode ^ present.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Iwad &&
          runtimeType == other.runtimeType &&
          fileName == other.fileName &&
          title == other.title &&
          path == other.path &&
          present == other.present;
}

/// An entry inside a profile's ordered load list.
class LoadEntry {
  final String path;
  final String name;
  final ModGroup group;
  final bool enabled;

  const LoadEntry({
    required this.path,
    required this.name,
    required this.group,
    required this.enabled,
  });

  @override
  int get hashCode =>
      path.hashCode ^ name.hashCode ^ group.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoadEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          group == other.group &&
          enabled == other.enabled;
}

/// Result of analysing a GZDoom crash/log file.
class LogAnalysis {
  final String summary;

  /// Mod paths/names most likely responsible, best guess first.
  final List<String> suspectMods;

  /// Notable lines/signals extracted from the log.
  final List<String> signals;

  const LogAnalysis({
    required this.summary,
    required this.suspectMods,
    required this.signals,
  });

  @override
  int get hashCode =>
      summary.hashCode ^ suspectMods.hashCode ^ signals.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogAnalysis &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          suspectMods == other.suspectMods &&
          signals == other.signals;
}

/// A single moddable file discovered on disk (.pk3/.wad/.pk7/.zip/.deh ...).
class ModFile {
  /// Absolute path; doubles as the stable identifier.
  final String path;
  final String name;
  final String extension_;
  final BigInt size;

  /// SHA-256, used for duplicate detection. Computed lazily/optionally.
  final String? sha256;
  final ModGroup group;
  final List<String> tags;

  const ModFile({
    required this.path,
    required this.name,
    required this.extension_,
    required this.size,
    this.sha256,
    required this.group,
    required this.tags,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      extension_.hashCode ^
      size.hashCode ^
      sha256.hashCode ^
      group.hashCode ^
      tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          extension_ == other.extension_ &&
          size == other.size &&
          sha256 == other.sha256 &&
          group == other.group &&
          tags == other.tags;
}

/// Graph nodes + edges for the dependency view.
class ModGraph {
  final List<GraphNode> nodes;
  final List<GraphEdge> edges;

  const ModGraph({required this.nodes, required this.edges});

  @override
  int get hashCode => nodes.hashCode ^ edges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModGraph &&
          runtimeType == other.runtimeType &&
          nodes == other.nodes &&
          edges == other.edges;
}

/// Logical grouping used both for UI sections and load-order heuristics.
enum ModGroup { gameplay, maps, visuals, audio, patch, other }

/// A saved build configuration.
class Profile {
  final String id;
  final String name;
  final String description;

  /// Path to the engine executable to use.
  final String? enginePath;

  /// IWAD filename or absolute path.
  final String? iwad;
  final List<LoadEntry> loadOrder;

  /// Extra raw command-line arguments.
  final List<String> extraArgs;
  final String createdAt;
  final String updatedAt;
  final String? lastPlayedAt;

  const Profile({
    required this.id,
    required this.name,
    required this.description,
    this.enginePath,
    this.iwad,
    required this.loadOrder,
    required this.extraArgs,
    required this.createdAt,
    required this.updatedAt,
    this.lastPlayedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      enginePath.hashCode ^
      iwad.hashCode ^
      loadOrder.hashCode ^
      extraArgs.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode ^
      lastPlayedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Profile &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          enginePath == other.enginePath &&
          iwad == other.iwad &&
          loadOrder == other.loadOrder &&
          extraArgs == other.extraArgs &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt &&
          lastPlayedAt == other.lastPlayedAt;
}

/// Diff between two profiles' load orders.
class ProfileDiff {
  final List<String> onlyInA;
  final List<String> onlyInB;
  final List<String> common;
  final bool reordered;

  const ProfileDiff({
    required this.onlyInA,
    required this.onlyInB,
    required this.common,
    required this.reordered,
  });

  @override
  int get hashCode =>
      onlyInA.hashCode ^
      onlyInB.hashCode ^
      common.hashCode ^
      reordered.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileDiff &&
          runtimeType == other.runtimeType &&
          onlyInA == other.onlyInA &&
          onlyInB == other.onlyInB &&
          common == other.common &&
          reordered == other.reordered;
}

/// A recommended mod to add to a build.
class Recommendation {
  final String path;
  final String name;
  final ModGroup group;
  final String reason;
  final double score;

  const Recommendation({
    required this.path,
    required this.name,
    required this.group,
    required this.reason,
    required this.score,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      name.hashCode ^
      group.hashCode ^
      reason.hashCode ^
      score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recommendation &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          name == other.name &&
          group == other.group &&
          reason == other.reason &&
          score == other.score;
}

/// Metadata for a saved profile snapshot.
class SnapshotMeta {
  final String id;
  final String label;
  final String createdAt;
  final BigInt entryCount;

  const SnapshotMeta({
    required this.id,
    required this.label,
    required this.createdAt,
    required this.entryCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ createdAt.hashCode ^ entryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SnapshotMeta &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          createdAt == other.createdAt &&
          entryCount == other.entryCount;
}

/// Per-profile stability tracking.
class Stability {
  final int launches;
  final int crashes;

  /// 0..=100; higher is more stable.
  final int rating;

  const Stability({
    required this.launches,
    required this.crashes,
    required this.rating,
  });

  @override
  int get hashCode => launches.hashCode ^ crashes.hashCode ^ rating.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Stability &&
          runtimeType == other.runtimeType &&
          launches == other.launches &&
          crashes == other.crashes &&
          rating == other.rating;
}
