// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A package entry in a DoomForge registry. The registry is a JSON document
/// (hosted anywhere, or local) of the shape `{ "packages": [PackageEntry...] }`.
///
/// This is deliberately a generic registry rather than scraping Doomworld/ModDB
/// HTML: those sites have no stable public API and their markup changes often,
/// so a maintained registry index is the robust integration point. A scraper
/// adapter can later populate such an index.
class PackageEntry {
  final String id;
  final String name;
  final String description;
  final String version;

  /// Direct download URL of the pk3/wad/zip.
  final String url;
  final List<String> tags;
  final String? homepage;

  const PackageEntry({
    required this.id,
    required this.name,
    required this.description,
    required this.version,
    required this.url,
    required this.tags,
    this.homepage,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      version.hashCode ^
      url.hashCode ^
      tags.hashCode ^
      homepage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PackageEntry &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          version == other.version &&
          url == other.url &&
          tags == other.tags &&
          homepage == other.homepage;
}
