// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../domain/models.dart';
import '../frb_generated.dart';
import '../services/net.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `base`, `e`

/// Store the per-user data directory (call once at startup from Dart).
Future<void> setDataDir({required String dataDir}) =>
    RustLib.instance.api.crateApiDoomforgeSetDataDir(dataDir: dataDir);

Future<List<ModFile>> scanMods({
  required String dir,
  required bool withHashes,
}) => RustLib.instance.api.crateApiDoomforgeScanMods(
  dir: dir,
  withHashes: withHashes,
);

Future<List<ModFile>> describeFiles({required List<String> paths}) =>
    RustLib.instance.api.crateApiDoomforgeDescribeFiles(paths: paths);

Future<List<DuplicateGroup>> findDuplicates({required List<ModFile> files}) =>
    RustLib.instance.api.crateApiDoomforgeFindDuplicates(files: files);

Future<List<String>> searchModContents({
  required List<ModFile> files,
  required String query,
}) => RustLib.instance.api.crateApiDoomforgeSearchModContents(
  files: files,
  query: query,
);

Future<List<Engine>> scanEngines({required String dir}) =>
    RustLib.instance.api.crateApiDoomforgeScanEngines(dir: dir);

Future<Engine> inspectEngine({required String path}) =>
    RustLib.instance.api.crateApiDoomforgeInspectEngine(path: path);

Future<List<Engine>> detectEngines() =>
    RustLib.instance.api.crateApiDoomforgeDetectEngines();

Future<List<Iwad>> checkIwads({required List<String> dirs}) =>
    RustLib.instance.api.crateApiDoomforgeCheckIwads(dirs: dirs);

Future<List<LoadEntry>> autoOrder({required List<LoadEntry> entries}) =>
    RustLib.instance.api.crateApiDoomforgeAutoOrder(entries: entries);

Future<List<Profile>> listProfiles() =>
    RustLib.instance.api.crateApiDoomforgeListProfiles();

Future<Profile> saveProfile({required Profile profile}) =>
    RustLib.instance.api.crateApiDoomforgeSaveProfile(profile: profile);

Future<void> deleteProfile({required String id}) =>
    RustLib.instance.api.crateApiDoomforgeDeleteProfile(id: id);

Future<void> exportProfile({required String id, required String dest}) =>
    RustLib.instance.api.crateApiDoomforgeExportProfile(id: id, dest: dest);

Future<Profile> importProfile({required String src}) =>
    RustLib.instance.api.crateApiDoomforgeImportProfile(src: src);

Future<ProfileDiff> compareProfiles({required Profile a, required Profile b}) =>
    RustLib.instance.api.crateApiDoomforgeCompareProfiles(a: a, b: b);

Future<String> launchProfile({
  required String engine,
  required Profile profile,
  required bool safeMode,
}) => RustLib.instance.api.crateApiDoomforgeLaunchProfile(
  engine: engine,
  profile: profile,
  safeMode: safeMode,
);

Future<String> dryRunProfile({
  required String engine,
  required Profile profile,
}) => RustLib.instance.api.crateApiDoomforgeDryRunProfile(
  engine: engine,
  profile: profile,
);

Future<CompatReport> evaluateCompat({required Profile profile}) =>
    RustLib.instance.api.crateApiDoomforgeEvaluateCompat(profile: profile);

Future<ModGraph> modGraph({required Profile profile}) =>
    RustLib.instance.api.crateApiDoomforgeModGraph(profile: profile);

Future<SnapshotMeta> createSnapshot({
  required Profile profile,
  required String label,
}) => RustLib.instance.api.crateApiDoomforgeCreateSnapshot(
  profile: profile,
  label: label,
);

Future<List<SnapshotMeta>> listSnapshots({required String profileId}) =>
    RustLib.instance.api.crateApiDoomforgeListSnapshots(profileId: profileId);

Future<Profile> restoreSnapshot({
  required String profileId,
  required String snapshotId,
}) => RustLib.instance.api.crateApiDoomforgeRestoreSnapshot(
  profileId: profileId,
  snapshotId: snapshotId,
);

Future<void> deleteSnapshot({
  required String profileId,
  required String snapshotId,
}) => RustLib.instance.api.crateApiDoomforgeDeleteSnapshot(
  profileId: profileId,
  snapshotId: snapshotId,
);

Future<Stability> recordOutcome({
  required String profileId,
  required bool crashed,
}) => RustLib.instance.api.crateApiDoomforgeRecordOutcome(
  profileId: profileId,
  crashed: crashed,
);

Future<Stability> getStability({required String profileId}) =>
    RustLib.instance.api.crateApiDoomforgeGetStability(profileId: profileId);

Future<List<Recommendation>> recommendMods({
  required List<ModFile> library_,
  required Profile profile,
  required int limit,
}) => RustLib.instance.api.crateApiDoomforgeRecommendMods(
  library_: library_,
  profile: profile,
  limit: limit,
);

Future<Profile> forgeBuild({required List<ModFile> library_, String? iwad}) =>
    RustLib.instance.api.crateApiDoomforgeForgeBuild(
      library_: library_,
      iwad: iwad,
    );

Future<String> generateReport({required Profile profile}) =>
    RustLib.instance.api.crateApiDoomforgeGenerateReport(profile: profile);

Future<void> saveText({required String dest, required String contents}) =>
    RustLib.instance.api.crateApiDoomforgeSaveText(
      dest: dest,
      contents: contents,
    );

Future<LogAnalysis> analyzeLogFile({
  required String path,
  required Profile profile,
}) => RustLib.instance.api.crateApiDoomforgeAnalyzeLogFile(
  path: path,
  profile: profile,
);

Future<LogAnalysis> analyzeLogText({
  required String text,
  required Profile profile,
}) => RustLib.instance.api.crateApiDoomforgeAnalyzeLogText(
  text: text,
  profile: profile,
);

Future<List<PackageEntry>> catalog() =>
    RustLib.instance.api.crateApiDoomforgeCatalog();

Future<String> installCatalog({required String url, required String modsDir}) =>
    RustLib.instance.api.crateApiDoomforgeInstallCatalog(
      url: url,
      modsDir: modsDir,
    );

Future<List<PackageEntry>> searchRegistry({
  required String source,
  required String query,
}) => RustLib.instance.api.crateApiDoomforgeSearchRegistry(
  source: source,
  query: query,
);

Future<String> installPackage({
  required String source,
  required String id,
  required String modsDir,
}) => RustLib.instance.api.crateApiDoomforgeInstallPackage(
  source: source,
  id: id,
  modsDir: modsDir,
);

Future<String> importByUrl({required String url, required String destDir}) =>
    RustLib.instance.api.crateApiDoomforgeImportByUrl(
      url: url,
      destDir: destDir,
    );

Future<List<String>> installFreedoom({required String iwadDir}) =>
    RustLib.instance.api.crateApiDoomforgeInstallFreedoom(iwadDir: iwadDir);

Future<String> installGzdoom({required String destDir}) =>
    RustLib.instance.api.crateApiDoomforgeInstallGzdoom(destDir: destDir);

Future<List<PackageEntry>> idgamesSearch({required String query}) =>
    RustLib.instance.api.crateApiDoomforgeIdgamesSearch(query: query);

Future<String> aiAnalyzeLog({
  required String apiKey,
  required String model,
  required String log,
  required List<String> loadOrder,
}) => RustLib.instance.api.crateApiDoomforgeAiAnalyzeLog(
  apiKey: apiKey,
  model: model,
  log: log,
  loadOrder: loadOrder,
);

Future<String> aiDescribeBuild({
  required String apiKey,
  required String model,
  required List<String> mods,
}) => RustLib.instance.api.crateApiDoomforgeAiDescribeBuild(
  apiKey: apiKey,
  model: model,
  mods: mods,
);
